language: php
php:
    - 5.6
    - 5.5

env:
  - SYMFONY_VERSION="~2.4"
  - SYMFONY_VERSION="~2.5"
  - SYMFONY_VERSION="~2.6"
  - SYMFONY_VERSION="~2.7"
  - SYMFONY_VERSION="~2.8"

before_script:
  - composer selfupdate
  - composer require symfony/framework-bundle:${SYMFONY_VERSION}
