language: php
php:
    - 7.0
    - 5.6
    - 5.5

env:
  - SYMFONY_VERSION="~2.7"
  - SYMFONY_VERSION="~2.8"
  - SYMFONY_VERSION="~3.0"
  - SYMFONY_VERSION="~3.1"

before_script:
  - composer selfupdate
  - composer require symfony/framework-bundle:${SYMFONY_VERSION}
